---
- name: Microshift builder | Prepare RHEL node to build RHEL for Edge ISO with Microshift
  hosts: builder
  become: true
  vars_prompt:
    - name: rhsm_user
      prompt: What is your RHSM Username (RHNID)?
      unsafe: true
      private: false

    - name: rhsm_password
      prompt: What is your RHSM Password?
      unsafe: true
      private: true

  tasks:
    - name: Microshift builder | Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"

    - name: Microshift builder | Install required packages
      ansible.builtin.yum:
        name:
          - osbuild-composer
          - composer-cli
          - cockpit-composer
          - bash-completion
          - podman
          - genisoimage
          - syslinux
          - lorax
          - firewalld
          - runc
          - containernetworking-cni
        state: present

    - name: Microshift builder | Ensure required services are enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - firewalld
        - osbuild-composer.socket
        - cockpit.socket

    - name: Microshift builder | Allow new services on firewalld
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        state: enabled
