---
- name: Trigger kickstarter 
  hosts: vm_host
  vars_files:
    - vars.yml
  tasks:
    - name: Check prerequisites
      ansible.builtin.import_tasks: 00_check_prerequisites.yml
        
    - name: Ensure lorax is installed
      ansible.builtin.dnf:
        name: lorax
        state: present
      become: true

    - name: Create instance dirs
      ansible.builtin.file:
        path: "{{ playbook_dir }}/rhel4edge/{{ item.cluster_name }}"
        state: directory
        recurse: true
      loop: "{{ rhel4edge_instances }}"

    - name: Trigger kickstart template
      ansible.builtin.template:
        src: kickstart.j2
        dest: "{{ playbook_dir }}/rhel4edge/{{ item.cluster_name }}/kickstart"
      loop: "{{ rhel4edge_instances }}"

    - name: Embed kickstart on freshly built image
      ansible.builtin.shell: mkksiso {{ playbook_dir }}/rhel4edge/{{ item.cluster_name }}/kickstart {{ playbook_dir }}/rhel4edge/r4e-microshift-installer.x86_64.iso /var/lib/libvirt/images/{{ item.cluster_name }}-r4e-microshift-installer.x86_64.iso
      args:
        creates: /var/lib/libvirt/images/{{ item.cluster_name }}-r4e-microshift-installer.x86_64.iso
      become: true
      loop: "{{ rhel4edge_instances }}"

    - name: Fire up the virtual machine
      ansible.builtin.shell: virt-install --memory 4096 --vcpus 2 --name {{ item.cluster_name }} --cdrom /var/lib/libvirt/images/{{ item.cluster_name }}-r4e-microshift-installer.x86_64.iso --disk size=20 --os-variant rhel8.5 --network=default --virt-type kvm --connect qemu:///system
      become: true
      loop: "{{ rhel4edge_instances }}"

    - name: Wait for VMs to settle
      ansible.builtin.pause:
        seconds: 240