---
- name: Trigger kickstarter
  hosts: vm_host
  vars_files:
    - vars.yml
  tasks:
    - name: Check prerequisites
      ansible.builtin.import_tasks: 00_check_prerequisites.yml

    - name: Find IP of the newly created hosts
      ansible.builtin.shell: virsh net-dhcp-leases default | grep {{ item.cluster_name }}
      become: true
      loop: "{{ rhel4edge_instances }}"
      register: ip_list

    - name: Set virtual inventory
      ansible.builtin.add_host:
        hostname: "{{ item.cluster_name }}"
        ansible_host: "{{ ip_list.results[loop_index].stdout | split(' ') | select() | list | ansible.utils.ipv4 | ansible.utils.ipaddr('address') | join }}"
        groups:
          - rhel4edge_hosts
        ansible_ssh_private_key_file: "{{ playbook_dir }}/id_rsa"
        ansible_user: redhat
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop: "{{ rhel4edge_instances }}"
      loop_control:
        index_var: loop_index

- name: Edge devices setup
  hosts: rhel4edge_hosts
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Fetch oc client
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        remote_src: true
        dest: /usr/local/bin
      become: true

    - name: Create .kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory

    - name: Store kubeconfig in user folder
      ansible.builtin.copy:
        src: /var/lib/microshift/resources/kubeadmin/kubeconfig
        dest: /home/redhat/.kube/config
        owner: redhat
        group: redhat
        remote_src: true
      become: true
